[tool.poetry]
name = "certification_tracker"
version = "2.0.0"
description = ""
authors = ["yshalsager <ysh-alsager@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
scrapy = "^2.5.0"
sqlalchemy = "^1.4.11"
python-telegram-bot = "^13.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
