[tool.poetry]
name = "certification_tracker"
version = "2.0.0"
description = ""
authors = ["yshalsager <ysh-alsager@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
scrapy = "^2.6.1"
sqlalchemy = "^1.4.36"
python-telegram-bot = "^13.12"

[tool.poetry.dev-dependencies]
pytest = "^7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
